services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3400:80"
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    restart: always
    env_file:
      - ./backend/.env